image: gitpod/workspace-full

# Commands that will run on workspace start
tasks:
    - name: Setup, Install & Build
      before: yarn global add @graphprotocol/graph-cli
      init: yarn install
      command: yarn build